#!/bin/bash


function start(){
    twistd web --port 7000 --wsgi app.app --logfile log.txt;
    echo "Anarcho started..."
}

function stop(){
    kill $(cat twistd.pid)
    echo "Anarcho stopped..."
}

command=$1

case "$command" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        stop
        start
        ;;
    *)
        echo "start|stop|restart"
        ;;
esac